# Generated by Django 3.2.7 on 2021-10-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('referrer', 'Referrer'), ('broker', 'Broker'), ('engineer', 'Engineer'), ('hire-company', 'Hire Company'), ('panel-solicitor', 'Panel Solicitor'), ('repairer', 'Repairer')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('post_code', models.CharField(max_length=16)),
                ('main_phone', models.CharField(max_length=20)),
                ('contact_phone', models.CharField(max_length=16)),
                ('fax', models.CharField(max_length=255)),
                ('emial', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('live', 'Live'), ('dead', 'Dead'), ('prospect', 'Prospect')], max_length=50)),
            ],
        ),
    ]
