# Generated by Django 3.2.7 on 2021-10-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='emial',
            new_name='email',
        ),
    ]
