# Generated by Django 3.2.8 on 2021-10-14 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0004_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('nrta', 'Non Fault RTA'), ('rta', 'Fault RTA'), ('hire-only', 'Hire Only')], max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='closed_date',
            field=models.DateTimeField(blank=True, verbose_name='File Closed Date'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='opened_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='File Opened by'),
        ),
    ]
