# Generated by Django 3.2.7 on 2021-10-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cross_hire', models.BooleanField()),
                ('vehicle_status', models.CharField(choices=[('available', 'Available'), ('on-hire', 'On hire'), ('off-fleet', 'Off Fleet'), ('in-repair', 'In Repair'), ('in-for-service', 'In for Service')], max_length=50)),
                ('currently_reserved', models.BooleanField(verbose_name='Is vehicle currently reserved?')),
                ('opened_by', models.CharField(max_length=255)),
                ('last_recorded_mileage', models.FloatField()),
                ('as_at', models.DateTimeField(verbose_name='as at')),
                ('category', models.CharField(blank=True, choices=[('saloon', 'Saloon'), ('purpose-built', 'Purpose Built'), ('mpv', 'MPV'), ('minibus', 'Minibus'), ('executive-e-class', 'Executive E Class'), ('executive-s-class', 'Executive S Class'), ('dual-control', 'Dual Control')], max_length=50, null=True, verbose_name='Vehicle category')),
                ('depot', models.CharField(choices=[('all-depots', 'All depots'), ('depot-1', 'Depot 1'), ('depot-2', 'Depot 2')], help_text='eg. DE51 BBY', max_length=25, verbose_name='Depot/Branch')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255, verbose_name='Colour')),
                ('cc', models.CharField(max_length=255, verbose_name='CC')),
                ('radio_code', models.CharField(max_length=255)),
                ('callibration_no', models.CharField(max_length=255)),
                ('number_of_doors', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('lpg', 'LPG'), ('petrol', 'Petrol')], max_length=20)),
                ('first_registration', models.DateTimeField()),
                ('tax_date', models.DateTimeField()),
                ('insurance_group', models.CharField(max_length=255)),
            ],
        ),
    ]
