# Generated by Django 3.2.7 on 2021-10-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20211003_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='licensing_authority',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='licensing_authority',
            field=models.ManyToManyField(blank=True, null=True, to='vehicles.LicensingAuthority'),
        ),
    ]
