# Generated by Django 3.2.7 on 2021-10-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_hire_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('tel_contact', models.CharField(max_length=255)),
                ('purchase_price', models.FloatField(help_text='in £')),
                ('purchase_price_vat', models.FloatField(help_text='in £', verbose_name='Purchase price VAT')),
                ('purchase_date', models.DateTimeField()),
                ('first_registration_date', models.DateTimeField()),
                ('agreement_no', models.CharField(max_length=255)),
                ('length_of_agreement', models.IntegerField(help_text='Mths')),
                ('lease_return_date', models.DateTimeField()),
                ('lease_return_miles', models.FloatField()),
                ('lease_miles_remaining', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('forename', models.CharField(max_length=255)),
                ('surname_or_company', models.CharField(max_length=255, verbose_name='Surname/Company')),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('tel_contact', models.CharField(max_length=255)),
                ('date_sold', models.DateTimeField()),
                ('mileage', models.FloatField()),
                ('guid_price', models.FloatField(help_text='in £')),
                ('sale_price', models.FloatField(help_text='in £')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('tel_contact', models.CharField(max_length=255)),
                ('purchase_price', models.FloatField(help_text='in £')),
                ('purchase_price_vat', models.FloatField(help_text='in £', verbose_name='Purchase price VAT')),
                ('purchase_date', models.DateTimeField()),
                ('first_registration_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='hire_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.hire'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.service'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='finance_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.finance'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sale_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.sale'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='supplier_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.supplier'),
        ),
    ]
