# Generated by Django 3.2.7 on 2021-10-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20211003_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='reserved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
