# Generated by Django 3.2.7 on 2021-10-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_hire_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='first_registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
