# Generated by Django 3.2.7 on 2021-10-04 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_finance_first_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='finance_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='vehicles.finance'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('lpg', 'LPG'), ('petrol', 'Petrol'), ('hybrid', 'Hybrid'), ('plug-in-hybrid', 'Plug-In Hybrid'), ('electric', 'Electric')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='hire_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='vehicles.hire'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='licensing_authority',
            field=models.ManyToManyField(blank=True, null=True, related_name='vehicle', to='vehicles.LicensingAuthority'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='vehicles.sale'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='service_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='vehicles.service'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='supplier_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='vehicles.supplier'),
        ),
    ]
