# Generated by Django 3.2.7 on 2021-10-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_auto_20211006_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='tax_date',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='first_registration',
            field=models.DateField(),
        ),
    ]
