# Generated by Django 3.2.7 on 2021-10-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_auto_20211006_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='first_registration',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='first_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
