# Generated by Django 3.2.7 on 2021-10-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_auto_20211006_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_v5c_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='revenue_weight',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax_status',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type_approval',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wheel_plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
