# Generated by Django 3.2.7 on 2021-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_auto_20211006_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tax_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
