# Generated by Django 3.2.7 on 2021-10-07 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0014_alter_vehicle_tax_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='callibration_no',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default='', max_length=255, verbose_name='VIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='opened_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
