# Generated by Django 3.2.7 on 2021-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_auto_20211007_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('lpg', 'LPG'), ('petrol', 'Petrol'), ('hybrid-electric', 'Hybrid Electric'), ('plug-in-hybrid', 'Plug-In Hybrid'), ('electricity', 'Electricity')], max_length=20),
        ),
    ]
