# Generated by Django 3.2.7 on 2021-10-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_alter_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='as_at',
            field=models.DateField(verbose_name=''),
        ),
    ]
