# Generated by Django 3.2.7 on 2021-10-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_alter_vehicle_as_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('saloon', 'Saloon'), ('purpose-built', 'Purpose Built'), ('minibus', 'Minibus'), ('executive-e-class', 'Executive E Class'), ('executive-s-class', 'Executive S Class'), ('dual-control', 'Dual Control'), ('mpv', 'MPV'), ('4x4', '4x4'), ('prestige', 'Prestige'), ('sports', 'Sports'), ('standard', 'Standard')], max_length=50, null=True, verbose_name='Car category'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(blank=True, choices=[('cars', 'Cars'), ('ommercial', 'Commercial'), ('private-hire-taxi', 'Private Hire/Taxi'), ('motorcycle', 'Motorcycle')], max_length=50, null=True, verbose_name='Vehicle category'),
        ),
    ]
