# Generated by Django 3.2.7 on 2021-10-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_auto_20211007_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(blank=True, choices=[('cars', 'Cars'), ('commercial', 'Commercial'), ('private-hire-taxi', 'Private Hire/Taxi'), ('motorcycle', 'Motorcycle')], max_length=50, null=True, verbose_name='Vehicle category'),
        ),
    ]
