# Generated by Django 3.2.7 on 2021-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_alter_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='depot',
            field=models.CharField(choices=[('all-depots', 'All depots'), ('depot-1', 'Depot 1'), ('depot-2', 'Depot 2'), ('571-cable-street', '571 Cable Street'), ('cross-hire', 'Cross Hire')], help_text='eg. DE51 BBY', max_length=25, verbose_name='Depot/Branch'),
        ),
    ]
