# Generated by Django 3.2.7 on 2021-10-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_auto_20211007_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='as_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_recorded_mileage',
        ),
        migrations.AddField(
            model_name='service',
            name='as_at',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='service',
            name='last_recorded_mileage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
