# Generated by Django 3.2.7 on 2021-10-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_auto_20211007_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_dvla_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
