# Generated by Django 3.2.7 on 2021-10-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0023_vehicle_vehicle_dvla_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='inner_sub_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Inner subcategory'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(blank=True, choices=[('Cars', 'Cars'), ('Commercial', 'Commercial'), ('Private Hire/Taxi', 'Private Hire/Taxi'), ('Motorcycle', 'Motorcycle')], max_length=255, null=True, verbose_name='Vehicle category'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subcategory'),
        ),
    ]
