# Generated by Django 3.2.7 on 2021-10-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0024_auto_20211009_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_cover',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
