# Generated by Django 3.2.7 on 2021-10-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0025_vehicle_insurance_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_cover',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
