# Generated by Django 3.2.7 on 2021-10-12 09:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0026_alter_vehicle_insurance_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('automatic', 'AUTOMATIC'), ('manual', 'MANUAL')], default='', max_length=16),
            preserve_default=False,
        ),
    ]
