# Generated by Django 3.2.8 on 2021-10-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0027_vehicle_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='inner_sub_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GTA Group Category'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehicle Type Category'),
        ),
    ]
